/*
 Navicat Premium Data Transfer

 Source Server         : CRVS-Live-Danger
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : 192.168.246.41:1521
 Source Schema         : CRVSPROD

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 14/09/2022 16:46:11
*/


-- ----------------------------
-- Table structure for AC_GROUPS
-- ----------------------------
DROP TABLE "CRVSPROD"."AC_GROUPS";
CREATE TABLE "CRVSPROD"."AC_GROUPS" (
  "GROUP_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "GROUP_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "EDUCATION_LEVEL_ID" NUMBER(19,0) VISIBLE,
  "GROUP_CODE" VARCHAR2(20 BYTE) VISIBLE,
  "INSTITUTE_TYPE" NUMBER(10,0) VISIBLE,
  "ENTERED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" TIMESTAMP(6) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for API_CREDENTIALS
-- ----------------------------
DROP TABLE "CRVSPROD"."API_CREDENTIALS";
CREATE TABLE "CRVSPROD"."API_CREDENTIALS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "ORGANIZATION" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "ACCESS_TOKEN" CLOB VISIBLE,
  "REFRESH_TOKEN" CLOB VISIBLE,
  "EXPIRED_TIME" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for API_EXPOSE_USERS
-- ----------------------------
DROP TABLE "CRVSPROD"."API_EXPOSE_USERS";
CREATE TABLE "CRVSPROD"."API_EXPOSE_USERS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ORGANIZATION" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "IP_ADDRESS" VARCHAR2(255 BYTE) VISIBLE,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PERMISSION" CLOB VISIBLE,
  "STATUS" CHAR(1 BYTE) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_NID_VERIFICATIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_NID_VERIFICATIONS";
CREATE TABLE "CRVSPROD"."ARC_NID_VERIFICATIONS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "HTTP_CODE" VARCHAR2(3 BYTE) VISIBLE,
  "REQ_DOB" DATE VISIBLE,
  "REQ_NID10_DIGIT" VARCHAR2(10 BYTE) VISIBLE,
  "REQ_NID17_DIGIT" VARCHAR2(17 BYTE) VISIBLE,
  "RESP_STATUS" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_STATUS_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_MESSAGE" VARCHAR2(255 BYTE) VISIBLE,
  "REQ_ID" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_DOB" DATE VISIBLE,
  "RESP_BIRTH_PLACE" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_NATIONAL_ID" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_DIVISION" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_DISTRICT" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_RMO" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_UPOZILA" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_POST_OFFICE" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_POSTAL_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_ADDITIONAL_MOUZA" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_ADDITIONAL_VILLAGE" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_HOLDING_NO" VARCHAR2(255 BYTE) VISIBLE,
  "RESP_REGION" VARCHAR2(255 BYTE) VISIBLE,
  "ROW_RESPONSE" CLOB VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "REQ_EIIN" NUMBER(10,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_ORG_STUDENT_RESPONSES
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_ORG_STUDENT_RESPONSES";
CREATE TABLE "CRVSPROD"."ARC_ORG_STUDENT_RESPONSES" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "BRN" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "DOB" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "FATHER_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "FATHER_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "MOTHER_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "MOTHER_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "RESPONSE_STATUS" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "REQUEST_RESPONSE" CLOB VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "ORIGINAL_REQUEST_RESPONSE" CLOB VISIBLE,
  "UID" VARCHAR2(20 BYTE) VISIBLE,
  "REQ_EIIN" NUMBER(10,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_ORG_VERIFICATIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_ORG_VERIFICATIONS";
CREATE TABLE "CRVSPROD"."ARC_ORG_VERIFICATIONS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "RES_CODE" VARCHAR2(3 BYTE) VISIBLE,
  "RES_UID" VARCHAR2(30 BYTE) VISIBLE,
  "RES_UBRN" VARCHAR2(50 BYTE) VISIBLE,
  "EIIN" VARCHAR2(10 BYTE) VISIBLE,
  "STD_CRVS_ID" VARCHAR2(30 BYTE) VISIBLE,
  "PARAM_STD_BRN" VARCHAR2(50 BYTE) VISIBLE,
  "PARAM_STD_DOB" VARCHAR2(30 BYTE) VISIBLE,
  "PARAM_FATHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "PARAM_MOTHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "RES_FATHER_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "RES_MOTHER_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "PARAM_STD_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "PARAM_STD_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "RES_STD_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "RES_STD_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "ROW_RESPONSE" CLOB VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "MESSAGE" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_STD_AVE_ATT_DATA
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_STD_AVE_ATT_DATA";
CREATE TABLE "CRVSPROD"."ARC_STD_AVE_ATT_DATA" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ATT_YEAR" VARCHAR2(10 BYTE) VISIBLE NOT NULL,
  "MONTH_ID" NUMBER(10,0) VISIBLE,
  "WORKING_DAY" NUMBER(10,0) VISIBLE,
  "ATTENDANCE_DAY" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_STD_CURRENT_ACADEMIC_INFO
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO";
CREATE TABLE "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "STD_CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ACADEMIC_YEAR" VARCHAR2(4 BYTE) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "UID" VARCHAR2(10 BYTE) VISIBLE,
  "SHIFT_ID" NUMBER(10,0) VISIBLE,
  "STD_SECTION" VARCHAR2(10 BYTE) VISIBLE,
  "CLASS_GROUP_ID" NUMBER(3,0) VISIBLE,
  "ADMISSION_CLASS" NUMBER(3,0) VISIBLE,
  "REG_NO" VARCHAR2(20 BYTE) VISIBLE,
  "ACADEMIC_ROLL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "ADMISSION_DATE" DATE VISIBLE,
  "VERSIONS_ID" NUMBER(3,0) VISIBLE,
  "SCHOLARSHIPS" NUMBER(3,0) VISIBLE,
  "MERIT_STIPEND" NUMBER(3,0) VISIBLE,
  "OTHER_SCHOLARSHIPS" NUMBER(3,0) VISIBLE,
  "TRANSFER_IN" NUMBER(3,0) VISIBLE,
  "REPEATER_ID" NUMBER(3,0) VISIBLE,
  "OPTIONAL_SUBJECT_1" NUMBER(3,0) VISIBLE,
  "OPTIONAL_SUBJECT_2" NUMBER(3,0) VISIBLE,
  "OPTIONAL_SUBJECT_3" NUMBER(3,0) VISIBLE,
  "OPTIONAL_SUBJECT_4" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_1" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_2" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_3" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_4" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_5" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_6" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_7" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_8" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_9" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_10" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_11" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_12" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_13" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_14" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_15" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_1" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_2" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_3" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_4" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_5" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_6" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_7" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_8" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_9" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_10" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_11" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_12" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_13" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_14" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_15" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_16" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_17" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_18" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_19" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_20" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_21" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_22" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_23" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_24" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_25" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_1" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_2" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_3" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_4" NUMBER(3,0) VISIBLE,
  "SUBJECT_RESULT_TOTAL_GPA" VARCHAR2(5 BYTE) VISIBLE,
  "STUDENT_SIG_DATE" DATE VISIBLE,
  "CLASS_TEACHER_SIG_DATE" DATE VISIBLE,
  "CLASS_TEACHER_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "CLASS_TEACHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "CLASS_TEACHER_NID" NUMBER(19,0) VISIBLE,
  "HEAD_TEACHER_SIG_DATE" DATE VISIBLE,
  "HEAD_TEACHER_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "HEAD_TEACHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "HEAD_TEACHER_NID_NO" NUMBER(19,0) VISIBLE,
  "HEAD_TEC_CET_STATUS" NUMBER(3,0) VISIBLE,
  "MIGRATION_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "ACTIVE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "PROMOTION_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."SRI_ID" IS 'student table column id';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."SCHOLARSHIPS" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."MERIT_STIPEND" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."OTHER_SCHOLARSHIPS" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."TRANSFER_IN" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."REPEATER_ID" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."HEAD_TEC_CET_STATUS" IS '1=no,2=yes';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."MIGRATION_STATUS" IS '0=no,1=yes';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."ACTIVE_STATUS" IS '1=active,0=dropout';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."PROMOTION_STATUS" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_CURRENT_ACADEMIC_INFO"."STATUS" IS '1=active,0=inactive';

-- ----------------------------
-- Table structure for ARC_STD_PREVIOUS_EXAM_RESULTS
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_STD_PREVIOUS_EXAM_RESULTS";
CREATE TABLE "CRVSPROD"."ARC_STD_PREVIOUS_EXAM_RESULTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "PREVIOUS_EXAM_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "PREVIOUS_EXAM_ROLL" VARCHAR2(20 BYTE) VISIBLE,
  "PREVIOUS_INS_EIIN" VARCHAR2(6 BYTE) VISIBLE,
  "PREVIOUS_INS_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "PREVIOUS_EXAM_BORD_ID" NUMBER(10,0) VISIBLE,
  "PREVIOUS_EXAM_GPA" VARCHAR2(6 BYTE) VISIBLE,
  "PREVIOUS_EXAM_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ARC_STD_REGISTRATION_INFO
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_STD_REGISTRATION_INFO";
CREATE TABLE "CRVSPROD"."ARC_STD_REGISTRATION_INFO" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "REGISTRATION_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "STD_CRVS_ID" VARCHAR2(15 BYTE) VISIBLE,
  "UID" VARCHAR2(10 BYTE) VISIBLE,
  "FULLNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "FULLNAME_ENGLISH" VARCHAR2(150 BYTE) VISIBLE,
  "BIN_BRN" VARCHAR2(17 BYTE) VISIBLE,
  "DOB" DATE VISIBLE,
  "GENDER" NUMBER(10,0) VISIBLE,
  "NATIONALITY" NUMBER(3,0) VISIBLE,
  "OTHER_NATIONALITY" VARCHAR2(20 BYTE) VISIBLE,
  "RELIGION" VARCHAR2(2 BYTE) VISIBLE,
  "REGISTER_CLASS" NUMBER(3,0) VISIBLE,
  "ACADEMIC_ROLL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "MARITAL_STATUS" VARCHAR2(1 BYTE) VISIBLE,
  "IS_DISABILITY" VARCHAR2(2 BYTE) VISIBLE,
  "DISABILITYTYPE" VARCHAR2(2 BYTE) VISIBLE,
  "BLOOD_GROUP" VARCHAR2(1 BYTE) VISIBLE,
  "SMALL_ETHNIC_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "SMALL_ETHNIC_GROUP_NAME" NUMBER(10,0) VISIBLE,
  "BIRTHPLACE" VARCHAR2(15 BYTE) VISIBLE,
  "MOTHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "MOTHER_UBRN" VARCHAR2(17 BYTE) VISIBLE,
  "MOTHER_DATE_OF_BIRTH" DATE VISIBLE,
  "MOTHERNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "MOTHERNAME_ENGLISH" VARCHAR2(150 BYTE) VISIBLE,
  "MOTHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "MOTHER_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "MOTHER_DEATH_DATE" VARCHAR2(4 BYTE) VISIBLE,
  "FATHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "FATHER_UBRN" VARCHAR2(17 BYTE) VISIBLE,
  "FATHER_DATE_OF_BIRTH" DATE VISIBLE,
  "FATHERNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "FATHERNAME_ENGLISH" VARCHAR2(150 BYTE) VISIBLE,
  "FATHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "FATHER_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "FATHER_DEATH_DATE" VARCHAR2(4 BYTE) VISIBLE,
  "PRESENTDIVISIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTDISTRICTID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTTHANAID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENT_CITY_CORPORATION" VARCHAR2(100 BYTE) VISIBLE,
  "PRESENTUNIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTAREAID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENT_ADDRESS" VARCHAR2(150 BYTE) VISIBLE,
  "PRESENTHOUSEHOLDNO" VARCHAR2(100 BYTE) VISIBLE,
  "PRESENT_POST_OFFICE" VARCHAR2(100 BYTE) VISIBLE,
  "PRESENTPOSTCODE" VARCHAR2(50 BYTE) VISIBLE,
  "PERMANENETDIVISIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTDISTTICTID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTTHANAID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENT_CITY_CORPORATION" VARCHAR2(100 BYTE) VISIBLE,
  "PERMANENTUNIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTAREAID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENT_ADDRESS" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTHOUSEHOLDNO" VARCHAR2(150 BYTE) VISIBLE,
  "PERMANENT_POST_OFFICE" VARCHAR2(100 BYTE) VISIBLE,
  "PERMANENTPOSTCODE" VARCHAR2(30 BYTE) VISIBLE,
  "GUARDIAN_NID" VARCHAR2(17 BYTE) VISIBLE,
  "GUARDIAN_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "GUARDIAN_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "RELATIONSHIP_WITH_GUARDIAN" NUMBER(10,0) VISIBLE,
  "GUARDIAN_MOBILE" VARCHAR2(11 BYTE) VISIBLE,
  "GUARDIAN_EMAIL" VARCHAR2(30 BYTE) VISIBLE,
  "CERTIFICATION_STATUS" NUMBER(3,0) VISIBLE,
  "GUARDIAN_SIG_DAY" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "ID_CARD_GENERATE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "IMAGE_FOLDER_PATH" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "STD_PROFILE_IMAGE" VARCHAR2(100 BYTE) VISIBLE,
  "STD_BIRTH_REG_NO_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "MOTHER_NID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "FATHER_NID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."NATIONALITY" IS '1=বাংলাদেশি,2=অন্যান্য';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."RELIGION" IS '1=ইসলাম,2=হিন্দু,3=বৌদ্ধ,4=খ্রিষ্টান,5=Not a believer,6=Refuse to disclose,7=অন্যান্য';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."REGISTER_CLASS" IS '6=৬ষ্ঠ,7=৭ম,8=৮ম,9=৯ম,5=10ম ,11=১১শ,12=১২শ';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."MARITAL_STATUS" IS '1=অবিবাহিত ,2=বিবাহিত ,3=বিধবা / বিপত্নীক,4=স্বামী-স্ত্রী পৃথক বসবাস ,5=তালাকপ্রাপ্ত / বিবাহ বিচ্ছেদ';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."IS_DISABILITY" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."DISABILITYTYPE" IS '1= বাক প্রতিবন্ধী ,2= দৃষ্টি প্রতিবন্ধী ,3= শ্রবন প্রতিবন্ধী,4= শারীরিক প্রতিবন্ধী,5= মানসিক প্রতিবন্ধী,6= সমস্যা নেই ';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."BLOOD_GROUP" IS '1=A+ ,2=A-,3=B+,4=B-,5=AB+,6=AB-,7=O+ ,8=O-';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."SMALL_ETHNIC_GROUP" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."SMALL_ETHNIC_GROUP_NAME" IS '1=সাওতাল,2=চাকমা,3=গারো,4=হাজং,5=চাক,6=কুকি,7=খেয়া,8=বম,9=মারমা,10=ত্রিপুরা,11=খাসিয়া,12=মনিপুরী,13=অন্যান্য,';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."RELATIONSHIP_WITH_GUARDIAN" IS '1=দাদা ,2=দাদি,3=ভাই ,4=বোন ,5= চাচা ,6=নানা ,7=নানী ,8=মামা,9=ফুফু ,10=খালা ,11=চাচাতো ভাই,12=মামাতো ভাই,13=চাচাতো বোন,14=মামাতো বোন,15=আইনগত';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."CERTIFICATION_STATUS" IS 'yes=2,no=1';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."ID_CARD_GENERATE_STATUS" IS '0=not generate id card,1=generated id card';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."STD_BIRTH_REG_NO_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."MOTHER_NID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."FATHER_NID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."ARC_STD_REGISTRATION_INFO"."STATUS" IS '0=pending,1=Verified,2=invalid';

-- ----------------------------
-- Table structure for ARC_STD_SUBJECT_WISE_RESULTS
-- ----------------------------
DROP TABLE "CRVSPROD"."ARC_STD_SUBJECT_WISE_RESULTS";
CREATE TABLE "CRVSPROD"."ARC_STD_SUBJECT_WISE_RESULTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_NUMBER" VARCHAR2(3 BYTE) VISIBLE,
  "GRADE_POINTS" VARCHAR2(5 BYTE) VISIBLE,
  "EXAM_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "SUBJECT_ID" NUMBER(10,0) VISIBLE,
  "OPTIONAL_SUBJECT_STATUS" NUMBER(3,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BOARDS
-- ----------------------------
DROP TABLE "CRVSPROD"."BOARDS";
CREATE TABLE "CRVSPROD"."BOARDS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "BOARD_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "BOARD_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "BOARD_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" CHAR(1 BYTE) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."BOARDS"."STATUS" IS '0 => inactive, 1 => active';

-- ----------------------------
-- Table structure for CRVS_IDS
-- ----------------------------
DROP TABLE "CRVSPROD"."CRVS_IDS";
CREATE TABLE "CRVSPROD"."CRVS_IDS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CRVS_ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "BOARD_CODE" NUMBER(10,0) VISIBLE NOT NULL,
  "STATUS" VARCHAR2(255 BYTE) VISIBLE DEFAULT '0'  NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE,
  "STUDENT_ID" NUMBER(10,0) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "YEAR" VARCHAR2(10 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."CRVS_IDS"."STATUS" IS '0 => not allocate; 1 => allocated';

-- ----------------------------
-- Table structure for DISTRICTS
-- ----------------------------
DROP TABLE "CRVSPROD"."DISTRICTS";
CREATE TABLE "CRVSPROD"."DISTRICTS" (
  "DISTRICT_ID" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "DIVISION_ID" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "DISTRICT_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "DISTRICT_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "DISTRICT_NAME_BN" VARCHAR2(150 BYTE) VISIBLE,
  "BOARD" VARCHAR2(50 BYTE) VISIBLE,
  "BOARD_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "MAD_BOARD_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" DATE VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" DATE VISIBLE,
  "DISTRICT_ID_OLD" VARCHAR2(50 BYTE) VISIBLE,
  "STATUS" NUMBER(1,0) VISIBLE DEFAULT '1'  NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DISTRICT_WISE_BOARDS
-- ----------------------------
DROP TABLE "CRVSPROD"."DISTRICT_WISE_BOARDS";
CREATE TABLE "CRVSPROD"."DISTRICT_WISE_BOARDS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "DIVISION_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "DISTRICT_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "BOARD_CODE" NUMBER(10,0) VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DIVISIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."DIVISIONS";
CREATE TABLE "CRVSPROD"."DIVISIONS" (
  "DIVISION_ID" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "DIVISION_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "DIVISION_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "DIVISION_NAME_BN" VARCHAR2(150 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" DATE VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" DATE VISIBLE,
  "DIVISION_ID_OLD" VARCHAR2(50 BYTE) VISIBLE,
  "STATUS" NUMBER(1,0) VISIBLE DEFAULT '1'  NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EDUCATIONS_LEVELS
-- ----------------------------
DROP TABLE "CRVSPROD"."EDUCATIONS_LEVELS";
CREATE TABLE "CRVSPROD"."EDUCATIONS_LEVELS" (
  "EDUCATION_LEVEL_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EDUCATION_LEVEL_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "EDUCATION_LEVEL_CODE" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "ENTERED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" TIMESTAMP(6) VISIBLE NOT NULL,
  "LAST_UPDATED_TIMESTAMP" TIMESTAMP(6) VISIBLE NOT NULL,
  "STATUS" NUMBER(1,0) VISIBLE DEFAULT '1'  NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EDUCATION_BOARD_RESPONSES
-- ----------------------------
DROP TABLE "CRVSPROD"."EDUCATION_BOARD_RESPONSES";
CREATE TABLE "CRVSPROD"."EDUCATION_BOARD_RESPONSES" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "STUDENT_REGISTRATION_ID" NUMBER(10,0) VISIBLE,
  "NAME" VARCHAR2(255 BYTE) VISIBLE,
  "DOB" VARCHAR2(255 BYTE) VISIBLE,
  "REGNO" VARCHAR2(255 BYTE) VISIBLE,
  "EXAM_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "BOARD_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "PASS_YEAR" VARCHAR2(255 BYTE) VISIBLE,
  "FATHER" VARCHAR2(255 BYTE) VISIBLE,
  "MOTHER" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" VARCHAR2(255 BYTE) VISIBLE,
  "REQUEST_RESPONSE" CLOB VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "REQ_EIIN" VARCHAR2(10 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EDUCATION_DEGREES
-- ----------------------------
DROP TABLE "CRVSPROD"."EDUCATION_DEGREES";
CREATE TABLE "CRVSPROD"."EDUCATION_DEGREES" (
  "EDUCATION_DEGREE_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EDUCATION_DEGREE_NAME" VARCHAR2(200 BYTE) VISIBLE,
  "EDUCATION_DEGREE_CODE" VARCHAR2(20 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" TIMESTAMP(6) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FAILED_JOBS
-- ----------------------------
DROP TABLE "CRVSPROD"."FAILED_JOBS";
CREATE TABLE "CRVSPROD"."FAILED_JOBS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CONNECTION" CLOB VISIBLE NOT NULL,
  "QUEUE" CLOB VISIBLE NOT NULL,
  "PAYLOAD" CLOB VISIBLE NOT NULL,
  "EXCEPTION" CLOB VISIBLE NOT NULL,
  "FAILED_AT" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for GEOGRAPHICAL_AREA
-- ----------------------------
DROP TABLE "CRVSPROD"."GEOGRAPHICAL_AREA";
CREATE TABLE "CRVSPROD"."GEOGRAPHICAL_AREA" (
  "GEOGRAPHICAL_STATUS" NUMBER(19,0) VISIBLE NOT NULL,
  "DETAILS" VARCHAR2(100 BYTE) VISIBLE,
  "DETAILS_BN" VARCHAR2(150 BYTE) VISIBLE,
  "UNIV_AREA" CHAR(255 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for INSTITUTES
-- ----------------------------
DROP TABLE "CRVSPROD"."INSTITUTES";
CREATE TABLE "CRVSPROD"."INSTITUTES" (
  "INSTITUTE_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "INSTITUTE_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "INSTITUTE_NAME_NEW" VARCHAR2(255 BYTE) VISIBLE,
  "INSTITUTE_NAME_BANGLA" VARCHAR2(400 BYTE) VISIBLE,
  "LOCATION" VARCHAR2(255 BYTE) VISIBLE,
  "E_MAIL" VARCHAR2(150 BYTE) VISIBLE,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "INSTITUTE_TYPE_ID" VARCHAR2(3 BYTE) VISIBLE,
  "EDUCATION_LEVEL_ID" VARCHAR2(3 BYTE) VISIBLE,
  "USER_ROLES" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STD_ID_CARD_GENERATE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "INS_ID_CARD_GENERATE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "DIVISION_ID" VARCHAR2(6 BYTE) VISIBLE,
  "DISTRICT_ID" VARCHAR2(6 BYTE) VISIBLE,
  "THANA_ID" VARCHAR2(10 BYTE) VISIBLE,
  "UNION_ID" VARCHAR2(30 BYTE) VISIBLE,
  "MAUZA_ID" VARCHAR2(12 BYTE) VISIBLE,
  "ESTABLISH_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "INSTITUTE_CODE" VARCHAR2(15 BYTE) VISIBLE,
  "MANAGEMENT" VARCHAR2(50 BYTE) VISIBLE,
  "FOR_WHOM" VARCHAR2(50 BYTE) VISIBLE,
  "STAT2000" VARCHAR2(50 BYTE) VISIBLE,
  "SHIFT_NO" VARCHAR2(50 BYTE) VISIBLE,
  "RECOGNITION" VARCHAR2(50 BYTE) VISIBLE,
  "MPO_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "MPO_CODE_SCHOOL" VARCHAR2(30 BYTE) VISIBLE,
  "GEOGRAPHICAL_STATUS" VARCHAR2(3 BYTE) VISIBLE,
  "GEO_CODE" VARCHAR2(15 BYTE) VISIBLE,
  "POST_OFFICE" VARCHAR2(50 BYTE) VISIBLE,
  "SCHOOL_CODE" VARCHAR2(10 BYTE) VISIBLE,
  "DAG_NO" VARCHAR2(10 BYTE) VISIBLE,
  "TECHNICAL_BRANCH_MPO_STATUS" VARCHAR2(3 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" VARCHAR2(50 BYTE) VISIBLE,
  "YEAR" VARCHAR2(50 BYTE) VISIBLE,
  "SCRIPT_STATUS" VARCHAR2(10 BYTE) VISIBLE,
  "STP_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "CASE_YN" VARCHAR2(10 BYTE) VISIBLE,
  "CASE_MONTH" VARCHAR2(15 BYTE) VISIBLE,
  "NEAREST_ADMIN_UNIT_DISTANT" VARCHAR2(10 BYTE) VISIBLE,
  "NEAREST_ADMIN_UNIT" VARCHAR2(10 BYTE) VISIBLE,
  "COMMERCE_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "SCIENCE_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "ARTS_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "HIGHREC" VARCHAR2(2 BYTE) VISIBLE,
  "MOBPHONE" VARCHAR2(50 BYTE) VISIBLE,
  "UNI_CODE_SCHOOL" VARCHAR2(50 BYTE) VISIBLE,
  "BOARD_CODE" VARCHAR2(10 BYTE) VISIBLE,
  "POLICE_STATION_DISTANCE_KM" VARCHAR2(10 BYTE) VISIBLE,
  "TELEPHONE" VARCHAR2(50 BYTE) VISIBLE,
  "AREA_STATUS1" VARCHAR2(50 BYTE) VISIBLE,
  "CONSTITUENCY" VARCHAR2(50 BYTE) VISIBLE,
  "ENGLISH_VER_YN" VARCHAR2(2 BYTE) VISIBLE,
  "VERIFIED_STATUS" VARCHAR2(40 BYTE) VISIBLE,
  "FAX" VARCHAR2(50 BYTE) VISIBLE,
  "STAT" VARCHAR2(50 BYTE) VISIBLE,
  "EDUCATION_LEVEL_ID_LOWEST" VARCHAR2(50 BYTE) VISIBLE,
  "NATIONALIZATION_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "COLLEGE_CODE" VARCHAR2(10 BYTE) VISIBLE,
  "WEB_SITE" VARCHAR2(255 BYTE) VISIBLE,
  "CUTDATE" VARCHAR2(100 BYTE) VISIBLE,
  "UPLOAD_HABU" VARCHAR2(100 BYTE) VISIBLE,
  "NOOF_UPDATE" VARCHAR2(100 BYTE) VISIBLE,
  "UNIV_EDUCATION_LEVEL_ID" VARCHAR2(100 BYTE) VISIBLE,
  "MEMBER_FEMALE" VARCHAR2(100 BYTE) VISIBLE,
  "MEMBER_TOTAL" VARCHAR2(50 BYTE) VISIBLE,
  "COMMITTEE_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "SAMISTER_NUM" VARCHAR2(50 BYTE) VISIBLE,
  "UNIV_EDU_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "UNIV_DEPT_NO" VARCHAR2(50 BYTE) VISIBLE,
  "UNIV_ANUSHAD_NO" VARCHAR2(50 BYTE) VISIBLE,
  "UNIV_INST_NO" VARCHAR2(50 BYTE) VISIBLE,
  "UNIV_BRANCH_NO" VARCHAR2(50 BYTE) VISIBLE,
  "SAMISTER_MONTH" VARCHAR2(50 BYTE) VISIBLE,
  "SAMISTER_DAY" VARCHAR2(50 BYTE) VISIBLE,
  "PERMITTED_DATE" VARCHAR2(50 BYTE) VISIBLE,
  "FORGINE_UNIV_ATTATH_YN" VARCHAR2(50 BYTE) VISIBLE,
  "POST_CODE" VARCHAR2(100 BYTE) VISIBLE,
  "UNIVERSITY_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "TECHNICAL_BRANCH_TYPE" VARCHAR2(3 BYTE) VISIBLE,
  "MPO_CODE_COLLEGE" VARCHAR2(20 BYTE) VISIBLE,
  "MPO_CODE_TECHNICAL" VARCHAR2(20 BYTE) VISIBLE,
  "MPO_CODE_MADRASAH" VARCHAR2(20 BYTE) VISIBLE,
  "STARTING_CLASS" VARCHAR2(5 BYTE) VISIBLE,
  "HIFJUL_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "MOJJABID_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "ARTS_COLLEGE" VARCHAR2(2 BYTE) VISIBLE,
  "SCIENCE_COLLEGE" VARCHAR2(2 BYTE) VISIBLE,
  "COMMERCE_COLLEGE" VARCHAR2(2 BYTE) VISIBLE,
  "ESTABLISH_DATE_VOC" VARCHAR2(50 BYTE) VISIBLE,
  "ESTABLISH_DATE_BM" VARCHAR2(50 BYTE) VISIBLE,
  "TECHNICAL_BRANCH_TYPE_BM" VARCHAR2(2 BYTE) VISIBLE,
  "STOP" VARCHAR2(50 BYTE) VISIBLE,
  "SOCIAL_SCIENCE_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "MPO_YN" VARCHAR2(1 BYTE) VISIBLE,
  "ARTS_GROUP_COL" VARCHAR2(50 BYTE) VISIBLE,
  "SCIENCE_GROUP_COL" VARCHAR2(50 BYTE) VISIBLE,
  "COMMERCE_GROUP_COL" VARCHAR2(50 BYTE) VISIBLE,
  "RECOGNITION_COL" VARCHAR2(50 BYTE) VISIBLE,
  "UNI_CODE_COLLEGE" VARCHAR2(50 BYTE) VISIBLE,
  "UNI_CODE_MADRASAH" VARCHAR2(50 BYTE) VISIBLE,
  "MPO_CODE_BM" VARCHAR2(15 BYTE) VISIBLE,
  "POLICE_STATION_DISTANCE_MTR" VARCHAR2(50 BYTE) VISIBLE,
  "NATIONAL_UNIVERSITY_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "TECHNICAL_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "ESTABLISH_DATE_HSCVOC" VARCHAR2(50 BYTE) VISIBLE,
  "ESTABLISH_DATE_COLLEGE" VARCHAR2(50 BYTE) VISIBLE,
  "ESTABLISH_DATE_DIPLOMA" VARCHAR2(50 BYTE) VISIBLE,
  "TECHNICAL_BRANCH_TYPE_HSCVOC" VARCHAR2(50 BYTE) VISIBLE,
  "TECHNICAL_BRANCH_BOTH" VARCHAR2(50 BYTE) VISIBLE,
  "CONSTITUTE_NO" VARCHAR2(50 BYTE) VISIBLE,
  "TEACH_TIME" VARCHAR2(50 BYTE) VISIBLE,
  "ESTABLISH_DATE_AGRI_DIPLOMA" VARCHAR2(50 BYTE) VISIBLE,
  "CASE_SUBJECT" VARCHAR2(50 BYTE) VISIBLE,
  "AREA_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "TEIIN" VARCHAR2(50 BYTE) VISIBLE,
  "GOVT_PRIMARY_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "THANA_NAME_NEW" VARCHAR2(150 BYTE) VISIBLE,
  "MAUZA_NAME_NEW" VARCHAR2(150 BYTE) VISIBLE,
  "UNION_NAME_NEW" VARCHAR2(150 BYTE) VISIBLE,
  "VERIFIED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "FINAL_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" VARCHAR2(50 BYTE) VISIBLE,
  "TOTAL_STUDENTS" VARCHAR2(20 BYTE) VISIBLE DEFAULT '0'
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."INSTITUTES"."USER_ROLES" IS '1=institute,2=teacher';
COMMENT ON COLUMN "CRVSPROD"."INSTITUTES"."STD_ID_CARD_GENERATE_STATUS" IS '0=not generate, 1=on progress, 2= successfully generate, 3 = error';
COMMENT ON COLUMN "CRVSPROD"."INSTITUTES"."INS_ID_CARD_GENERATE_STATUS" IS '1=ID CARD GENERATE,0=ID CARD Not GENERATE';

-- ----------------------------
-- Table structure for INSTITUTES_TYPES
-- ----------------------------
DROP TABLE "CRVSPROD"."INSTITUTES_TYPES";
CREATE TABLE "CRVSPROD"."INSTITUTES_TYPES" (
  "INSTITUTE_TYPE_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "INSTITUTE_TYPE_NAME" VARCHAR2(200 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" TIMESTAMP(6) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for INSTITUTES_USER
-- ----------------------------
DROP TABLE "CRVSPROD"."INSTITUTES_USER";
CREATE TABLE "CRVSPROD"."INSTITUTES_USER" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "TEACHER_ID" VARCHAR2(11 BYTE) VISIBLE,
  "EIIN" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "NAME" VARCHAR2(150 BYTE) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(30 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PHONE" VARCHAR2(11 BYTE) VISIBLE NOT NULL,
  "USER_ROLES" NUMBER(3,0) VISIBLE NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "NID" VARCHAR2(20 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."INSTITUTES_USER"."USER_ROLES" IS '1=institute,2=teacher';

-- ----------------------------
-- Table structure for INSTITUTE_TEACHERS
-- ----------------------------
DROP TABLE "CRVSPROD"."INSTITUTE_TEACHERS";
CREATE TABLE "CRVSPROD"."INSTITUTE_TEACHERS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PHONE" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "NID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "STATUS" CHAR(1 BYTE) VISIBLE DEFAULT '1'   NOT NULL,
  "TEACHER_TYPE" VARCHAR2(15 BYTE) VISIBLE DEFAULT 'TEACHER'   NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "EIIN" NUMBER(6,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."INSTITUTE_TEACHERS"."TEACHER_TYPE" IS 'Teacher & Headmaster';

-- ----------------------------
-- Table structure for JOBS
-- ----------------------------
DROP TABLE "CRVSPROD"."JOBS";
CREATE TABLE "CRVSPROD"."JOBS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "QUEUE" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "PAYLOAD" CLOB VISIBLE NOT NULL,
  "ATTEMPTS" NUMBER(3,0) VISIBLE NOT NULL,
  "RESERVED_AT" NUMBER(10,0) VISIBLE,
  "AVAILABLE_AT" NUMBER(10,0) VISIBLE NOT NULL,
  "CREATED_AT" NUMBER(10,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LOOKUP_AREA_STATUS1
-- ----------------------------
DROP TABLE "CRVSPROD"."LOOKUP_AREA_STATUS1";
CREATE TABLE "CRVSPROD"."LOOKUP_AREA_STATUS1" (
  "AREA_STATUS1" NUMBER(19,0) VISIBLE NOT NULL,
  "DETAILS" VARCHAR2(255 BYTE) VISIBLE,
  "DETAILS_BN" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MANAGEMENTS
-- ----------------------------
DROP TABLE "CRVSPROD"."MANAGEMENTS";
CREATE TABLE "CRVSPROD"."MANAGEMENTS" (
  "MANAGEMENT" NUMBER(19,0) VISIBLE NOT NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) VISIBLE,
  "DESCRIPTION_BN" VARCHAR2(100 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MAUZAS
-- ----------------------------
DROP TABLE "CRVSPROD"."MAUZAS";
CREATE TABLE "CRVSPROD"."MAUZAS" (
  "MAUZA_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "UNION_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "MAUZA_ID_NEW" VARCHAR2(50 BYTE) VISIBLE,
  "UNION_ID_NEW" VARCHAR2(50 BYTE) VISIBLE,
  "MAUZA_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "MAUZA_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "MAUZA_NAMEB" VARCHAR2(255 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" DATE VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" DATE VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MIGRATIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."MIGRATIONS";
CREATE TABLE "CRVSPROD"."MIGRATIONS" (
  "ID" NUMBER(10,0) VISIBLE NOT NULL,
  "MIGRATION" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "BATCH" NUMBER(10,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MODEL_HAS_PERMISSIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."MODEL_HAS_PERMISSIONS";
CREATE TABLE "CRVSPROD"."MODEL_HAS_PERMISSIONS" (
  "PERMISSION_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "MODEL_TYPE" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "MODEL_ID" NUMBER(19,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MODEL_HAS_ROLES
-- ----------------------------
DROP TABLE "CRVSPROD"."MODEL_HAS_ROLES";
CREATE TABLE "CRVSPROD"."MODEL_HAS_ROLES" (
  "ROLE_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "MODEL_TYPE" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "MODEL_ID" NUMBER(19,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."PERMISSIONS";
CREATE TABLE "CRVSPROD"."PERMISSIONS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "GUARD_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for POURASAVAS
-- ----------------------------
DROP TABLE "CRVSPROD"."POURASAVAS";
CREATE TABLE "CRVSPROD"."POURASAVAS" (
  "POURA_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "THANA_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "POURA_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "POURA_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "POURA_NAMEB" VARCHAR2(150 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" DATE VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" DATE VISIBLE,
  "STATUS" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ROLES
-- ----------------------------
DROP TABLE "CRVSPROD"."ROLES";
CREATE TABLE "CRVSPROD"."ROLES" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "GUARD_NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ROLE_HAS_PERMISSIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."ROLE_HAS_PERMISSIONS";
CREATE TABLE "CRVSPROD"."ROLE_HAS_PERMISSIONS" (
  "PERMISSION_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ROLE_ID" NUMBER(19,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SESSIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."SESSIONS";
CREATE TABLE "CRVSPROD"."SESSIONS" (
  "ID" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "USER_ID" NUMBER(19,0) VISIBLE,
  "IP_ADDRESS" VARCHAR2(45 BYTE) VISIBLE,
  "USER_AGENT" CLOB VISIBLE,
  "PAYLOAD" CLOB VISIBLE NOT NULL,
  "LAST_ACTIVITY" NUMBER(10,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_ACHIEVEMENTS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_ACHIEVEMENTS";
CREATE TABLE "CRVSPROD"."STD_ACHIEVEMENTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME_EN" VARCHAR2(100 BYTE) VISIBLE,
  "NAME_BN" VARCHAR2(100 BYTE) VISIBLE,
  "PARENT_ID" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_ATTD_WORKING_DAY
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_ATTD_WORKING_DAY";
CREATE TABLE "CRVSPROD"."STD_ATTD_WORKING_DAY" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ATT_MONTH" NUMBER(10,0) VISIBLE,
  "ATT_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "WORKING_DAY" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "EIIN" NUMBER(10,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_ATTENDANCES_CHILD
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_ATTENDANCES_CHILD";
CREATE TABLE "CRVSPROD"."STD_ATTENDANCES_CHILD" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "STD_CRVS_ID" VARCHAR2(16 BYTE) VISIBLE NOT NULL,
  "UID" VARCHAR2(10 BYTE) VISIBLE,
  "ATTENDANCE_PARENT_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ATTENDANCE_STATUS" CHAR(1 BYTE) VISIBLE NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_ATTENDANCES_CHILD"."SRI_ID" IS 'student table id';
COMMENT ON COLUMN "CRVSPROD"."STD_ATTENDANCES_CHILD"."SCAI_ID" IS 'student Current table id';
COMMENT ON COLUMN "CRVSPROD"."STD_ATTENDANCES_CHILD"."STD_CRVS_ID" IS 'custom generated id';
COMMENT ON COLUMN "CRVSPROD"."STD_ATTENDANCES_CHILD"."ATTENDANCE_PARENT_ID" IS 'attendance table id';

-- ----------------------------
-- Table structure for STD_ATTENDANCES_PARENT
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_ATTENDANCES_PARENT";
CREATE TABLE "CRVSPROD"."STD_ATTENDANCES_PARENT" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(3,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "ATTENDANCE_DATE" DATE VISIBLE NOT NULL,
  "YEAR" VARCHAR2(4 BYTE) VISIBLE NOT NULL,
  "ATTENDANCE_MONTH" VARCHAR2(2 BYTE) VISIBLE NOT NULL,
  "GIRLS_ATTENDANCE_COUNT" NUMBER(10,0) VISIBLE NOT NULL,
  "BOYS_ATTENDANCE_COUNT" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_ABSENT_COUNT" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_ATTEND_COUNT" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_STUDENT" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_GIRLS_COUNT" NUMBER(10,0) VISIBLE NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_AVERAGE_ATTENDANCE_DATA
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_AVERAGE_ATTENDANCE_DATA";
CREATE TABLE "CRVSPROD"."STD_AVERAGE_ATTENDANCE_DATA" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "ATT_YEAR" VARCHAR2(10 BYTE) VISIBLE,
  "MONTH_ID" NUMBER(10,0) VISIBLE,
  "WORKING_DAY" NUMBER(10,0) VISIBLE,
  "ATTENDANCE_DAY" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_CATEGORYS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_CATEGORYS";
CREATE TABLE "CRVSPROD"."STD_CATEGORYS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME_EN" VARCHAR2(100 BYTE) VISIBLE,
  "NAME_BN" VARCHAR2(100 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_CLASSES
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_CLASSES";
CREATE TABLE "CRVSPROD"."STD_CLASSES" (
  "ID" NUMBER(10,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "STATUS" VARCHAR2(255 BYTE) VISIBLE DEFAULT '1'  NOT NULL,
  "PRIORITY_BY" NUMBER(10,0) VISIBLE,
  "PARENT_ID" NUMBER(10,0) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "NAME_BN" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_CURRENT_ACADEMIC_INFO
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO";
CREATE TABLE "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "STD_CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ACADEMIC_YEAR" VARCHAR2(4 BYTE) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "UID" VARCHAR2(10 BYTE) VISIBLE,
  "SHIFT_ID" NUMBER(10,0) VISIBLE,
  "STD_SECTION" VARCHAR2(10 BYTE) VISIBLE,
  "CLASS_GROUP_ID" NUMBER(19,0) VISIBLE,
  "ADMISSION_CLASS" NUMBER(3,0) VISIBLE,
  "REG_NO" VARCHAR2(20 BYTE) VISIBLE,
  "ACADEMIC_ROLL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "ADMISSION_DATE" DATE VISIBLE,
  "VERSIONS_ID" NUMBER(3,0) VISIBLE,
  "SCHOLARSHIPS" NUMBER(3,0) VISIBLE,
  "MERIT_STIPEND" NUMBER(3,0) VISIBLE,
  "OTHER_SCHOLARSHIPS" NUMBER(3,0) VISIBLE,
  "TRANSFER_IN" NUMBER(3,0) VISIBLE,
  "REPEATER_ID" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_1" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_2" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_3" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_4" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_5" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_6" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_7" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_8" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_9" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_10" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_11" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_12" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_13" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_14" NUMBER(3,0) VISIBLE,
  "HOBBY_ID_15" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_1" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_2" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_3" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_4" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_5" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_6" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_7" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_8" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_9" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_10" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_11" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_12" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_13" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_14" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_15" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_16" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_17" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_18" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_19" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_20" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_21" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_22" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_23" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_24" NUMBER(3,0) VISIBLE,
  "COCURRICULAR_ID_25" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_1_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_2_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_1" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_2" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_3" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_4" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_5" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_6" NUMBER(3,0) VISIBLE,
  "LEVEL_3_ACHIEVEMENT_7" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_1_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_2_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_1" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_2" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_3" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_4" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_5" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_6" NUMBER(3,0) VISIBLE,
  "LEVEL_3_PARTICIPATION_ID_7" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_1" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_2" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_3" NUMBER(3,0) VISIBLE,
  "STD_CATEGORY_4" NUMBER(3,0) VISIBLE,
  "SUBJECT_RESULT_TOTAL_GPA" VARCHAR2(5 BYTE) VISIBLE,
  "STUDENT_SIG_DATE" DATE VISIBLE,
  "CLASS_TEACHER_SIG_DATE" DATE VISIBLE,
  "CLASS_TEACHER_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "CLASS_TEACHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "CLASS_TEACHER_NID" NUMBER(19,0) VISIBLE,
  "HEAD_TEACHER_SIG_DATE" DATE VISIBLE,
  "HEAD_TEACHER_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "HEAD_TEACHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "HEAD_TEACHER_NID_NO" NUMBER(19,0) VISIBLE,
  "HEAD_TEC_CET_STATUS" NUMBER(3,0) VISIBLE,
  "MIGRATION_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "ACTIVE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "PROMOTION_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."SRI_ID" IS 'student table column id';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."SCHOLARSHIPS" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."MERIT_STIPEND" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."OTHER_SCHOLARSHIPS" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."TRANSFER_IN" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."REPEATER_ID" IS '1=yes,2=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."HEAD_TEC_CET_STATUS" IS '1=no,2=yes';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."MIGRATION_STATUS" IS '0=no,1=yes';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."ACTIVE_STATUS" IS '1=active,0=dropout';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."PROMOTION_STATUS" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."STD_CURRENT_ACADEMIC_INFO"."STATUS" IS '1=active,0=inactive';

-- ----------------------------
-- Table structure for STD_EXAMS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_EXAMS";
CREATE TABLE "CRVSPROD"."STD_EXAMS" (
  "ID" NUMBER(10,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(250 BYTE) VISIBLE,
  "EXAM_TYPE" NUMBER(3,0) VISIBLE,
  "BLOCK_TYPE" NUMBER(3,0) VISIBLE,
  "CONFLICT_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "PRE_CONFLICT_EXAM_ID" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."ID" IS 'G=1,M=2,G+M=3,GV=4,MV=5,GV+MV=6';
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."EXAM_TYPE" IS '1= public,0= barshik';
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."BLOCK_TYPE" IS '1= subject wise exam,2= Previous wise exam';
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."CONFLICT_STATUS" IS '0 = No same exam like, 1 = same exam found';
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."PRE_CONFLICT_EXAM_ID" IS 'if old ten than id will be ssc exam';
COMMENT ON COLUMN "CRVSPROD"."STD_EXAMS"."STATUS" IS '0=active,1=inactive';

-- ----------------------------
-- Table structure for STD_EXAM_DETAILS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_EXAM_DETAILS";
CREATE TABLE "CRVSPROD"."STD_EXAM_DETAILS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EXAM_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "INSTITUTE_TYPE_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_COMPULSORY" NUMBER(10,0) VISIBLE,
  "TOTAL_ELECTIVE" NUMBER(10,0) VISIBLE,
  "TOTAL_OPTIONAL" NUMBER(10,0) VISIBLE,
  "AC_GROUP_ID" NUMBER(10,0) VISIBLE,
  "PARENT_EXAM_ID" CLOB VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_EXTRA_CO_CURRICULAR_EXAM
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_EXTRA_CO_CURRICULAR_EXAM";
CREATE TABLE "CRVSPROD"."STD_EXTRA_CO_CURRICULAR_EXAM" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME_EN" VARCHAR2(100 BYTE) VISIBLE,
  "NAME_BN" VARCHAR2(100 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_EXTRA_CO_CURRICULAR_EXAM"."STATUS" IS 'all=0,male=1,female=2';

-- ----------------------------
-- Table structure for STD_GRADING_SYSTEMS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_GRADING_SYSTEMS";
CREATE TABLE "CRVSPROD"."STD_GRADING_SYSTEMS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "GRADE" VARCHAR2(255 BYTE) VISIBLE DEFAULT 'F'  NOT NULL,
  "GRADE_POINT" NUMBER(8,1) VISIBLE DEFAULT '0'  NOT NULL,
  "N_MIN" NUMBER(10,0) VISIBLE DEFAULT '0'  NOT NULL,
  "N_MAX" NUMBER(10,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STATUS" CHAR(1 BYTE) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_GRADING_SYSTEMS"."GRADE" IS 'A+, A, A-, B, C, D, F';
COMMENT ON COLUMN "CRVSPROD"."STD_GRADING_SYSTEMS"."GRADE_POINT" IS 'grade A+ = 5';

-- ----------------------------
-- Table structure for STD_HOBBYS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_HOBBYS";
CREATE TABLE "CRVSPROD"."STD_HOBBYS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME_EN" VARCHAR2(100 BYTE) VISIBLE,
  "NAME_BN" VARCHAR2(100 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_MIGRATION
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_MIGRATION";
CREATE TABLE "CRVSPROD"."STD_MIGRATION" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "TARGET_EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "CURRENT_EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "REQUEST_BY" VARCHAR2(20 BYTE) VISIBLE,
  "APPROVE_BY" VARCHAR2(6 BYTE) VISIBLE,
  "REQUEST_AT" DATE VISIBLE,
  "APPROVE_AT" DATE VISIBLE,
  "STATUS" VARCHAR2(1 BYTE) VISIBLE DEFAULT 'P'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "REQUEST_REMARK" CLOB VISIBLE,
  "APPROVE_REMARK" CLOB VISIBLE,
  "MIGRATION_TRACKING_CODE" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_MIGRATION"."STATUS" IS 'P=pending,Y=yes,N=no';

-- ----------------------------
-- Table structure for STD_PARENT_OCCUPATIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_PARENT_OCCUPATIONS";
CREATE TABLE "CRVSPROD"."STD_PARENT_OCCUPATIONS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "GROUP_NAME_BN" VARCHAR2(400 BYTE) VISIBLE,
  "GROUP_NAME_EN" VARCHAR2(200 BYTE) VISIBLE,
  "PARENT_ID" NUMBER(10,0) VISIBLE DEFAULT '0'  NOT NULL,
  "MAJOR_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "SUB_MAJOR_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "MINOR_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "UNIT_CODE" VARCHAR2(255 BYTE) VISIBLE,
  "GROUP" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_PARTICIPATIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_PARTICIPATIONS";
CREATE TABLE "CRVSPROD"."STD_PARTICIPATIONS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME_EN" VARCHAR2(100 BYTE) VISIBLE,
  "NAME_BN" VARCHAR2(100 BYTE) VISIBLE,
  "PARENT_ID" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_PREVIOUS_EXAM_RESULTS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_PREVIOUS_EXAM_RESULTS";
CREATE TABLE "CRVSPROD"."STD_PREVIOUS_EXAM_RESULTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SRI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "PREVIOUS_EXAM_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "PREVIOUS_EXAM_ROLL" VARCHAR2(20 BYTE) VISIBLE,
  "PREVIOUS_INS_EIIN" VARCHAR2(6 BYTE) VISIBLE,
  "PREVIOUS_INS_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "PREVIOUS_EXAM_BORD_ID" NUMBER(10,0) VISIBLE,
  "PREVIOUS_EXAM_GPA" VARCHAR2(20 BYTE) VISIBLE,
  "PREVIOUS_EXAM_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STD_REGISTRATION_INFO
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_REGISTRATION_INFO";
CREATE TABLE "CRVSPROD"."STD_REGISTRATION_INFO" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "EIIN" VARCHAR2(6 BYTE) VISIBLE NOT NULL,
  "REGISTRATION_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "STD_CRVS_ID" VARCHAR2(15 BYTE) VISIBLE,
  "UID" VARCHAR2(10 BYTE) VISIBLE,
  "FULLNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "FULLNAME_ENGLISH" VARCHAR2(100 BYTE) VISIBLE,
  "BIN_BRN" VARCHAR2(17 BYTE) VISIBLE,
  "DOB" DATE VISIBLE,
  "GENDER" NUMBER(10,0) VISIBLE,
  "NATIONALITY" NUMBER(3,0) VISIBLE,
  "OTHER_NATIONALITY" VARCHAR2(20 BYTE) VISIBLE,
  "RELIGION" VARCHAR2(2 BYTE) VISIBLE,
  "REGISTER_CLASS" NUMBER(3,0) VISIBLE,
  "ACADEMIC_ROLL_NO" VARCHAR2(10 BYTE) VISIBLE,
  "MARITAL_STATUS" VARCHAR2(1 BYTE) VISIBLE,
  "IS_DISABILITY" VARCHAR2(2 BYTE) VISIBLE,
  "DISABILITYTYPE" VARCHAR2(2 BYTE) VISIBLE,
  "BLOOD_GROUP" VARCHAR2(1 BYTE) VISIBLE,
  "SMALL_ETHNIC_GROUP" VARCHAR2(2 BYTE) VISIBLE,
  "SMALL_ETHNIC_GROUP_NAME" NUMBER(10,0) VISIBLE,
  "BIRTHPLACE" VARCHAR2(15 BYTE) VISIBLE,
  "MOTHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "MOTHER_UBRN" VARCHAR2(17 BYTE) VISIBLE,
  "MOTHER_DATE_OF_BIRTH" DATE VISIBLE,
  "MOTHERNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "MOTHERNAME_ENGLISH" VARCHAR2(150 BYTE) VISIBLE,
  "MOTHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "MOTHER_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "MOTHER_DEATH_DATE" VARCHAR2(4 BYTE) VISIBLE,
  "FATHER_NID" VARCHAR2(17 BYTE) VISIBLE,
  "FATHER_UBRN" VARCHAR2(17 BYTE) VISIBLE,
  "FATHER_DATE_OF_BIRTH" DATE VISIBLE,
  "FATHERNAME_BANGLA" VARCHAR2(150 BYTE) VISIBLE,
  "FATHERNAME_ENGLISH" VARCHAR2(150 BYTE) VISIBLE,
  "FATHER_MOBILE_NO" VARCHAR2(11 BYTE) VISIBLE,
  "FATHER_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "FATHER_DEATH_DATE" VARCHAR2(4 BYTE) VISIBLE,
  "PRESENTDIVISIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTDISTRICTID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTTHANAID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENT_CITY_CORPORATION" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTUNIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENTAREAID" VARCHAR2(35 BYTE) VISIBLE,
  "PRESENT_ADDRESS" VARCHAR2(150 BYTE) VISIBLE,
  "PRESENTHOUSEHOLDNO" VARCHAR2(255 BYTE) VISIBLE,
  "PRESENT_POST_OFFICE" VARCHAR2(150 BYTE) VISIBLE,
  "PRESENTPOSTCODE" VARCHAR2(20 BYTE) VISIBLE,
  "PERMANENETDIVISIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTDISTTICTID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTTHANAID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENT_CITY_CORPORATION" VARCHAR2(150 BYTE) VISIBLE,
  "PERMANENTUNIONID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENTAREAID" VARCHAR2(35 BYTE) VISIBLE,
  "PERMANENT_ADDRESS" VARCHAR2(150 BYTE) VISIBLE,
  "PERMANENTHOUSEHOLDNO" VARCHAR2(150 BYTE) VISIBLE,
  "PERMANENT_POST_OFFICE" VARCHAR2(100 BYTE) VISIBLE,
  "PERMANENTPOSTCODE" VARCHAR2(100 BYTE) VISIBLE,
  "GUARDIAN_NID" VARCHAR2(17 BYTE) VISIBLE,
  "GUARDIAN_NAME" VARCHAR2(150 BYTE) VISIBLE,
  "GUARDIAN_DATE_OF_BIRTH" DATE VISIBLE,
  "GUARDIAN_PROFESSION" VARCHAR2(30 BYTE) VISIBLE,
  "GUARDIAN_SIG_DATE" VARCHAR2(30 BYTE) VISIBLE,
  "RELATIONSHIP_WITH_GUARDIAN" NUMBER(10,0) VISIBLE,
  "GUARDIAN_MOBILE" VARCHAR2(11 BYTE) VISIBLE,
  "CERTIFICATION_STATUS" NUMBER(3,0) VISIBLE,
  "ID_CARD_GENERATE_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "IMAGE_FOLDER_PATH" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "STD_PROFILE_IMAGE" VARCHAR2(100 BYTE) VISIBLE,
  "FM_NID_FOUND_STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "STD_BIRTH_REG_NO_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "UID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "MOTHER_NID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "FATHER_NID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "GUARDIAN_NID_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "TEMP_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "TAB_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "BRN_FATHER_NAME_EN_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "BRN_FATHER_NAME_BN_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "BRN_MOTHER_NAME_EN_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "BRN_MOTHER_NAME_BN_STATUS" NUMBER(3,0) VISIBLE DEFAULT '0'  NOT NULL,
  "IS_CLICKED_BOARD_RESPONSE_CONFIRM" CHAR(1 BYTE) VISIBLE DEFAULT '0'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE,
  "ORG_NAME_BANGLA" VARCHAR2(255 BYTE) VISIBLE,
  "ORG_NAME_ENGLISH" VARCHAR2(255 BYTE) VISIBLE,
  "WRITE_BIRTH_PLACE" VARCHAR2(255 BYTE) VISIBLE,
  "CRVS_MOTHER_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "CRVS_MOTHER_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "CRVS_FATHER_NAME_BN" VARCHAR2(255 BYTE) VISIBLE,
  "CRVS_FATHER_NAME_EN" VARCHAR2(255 BYTE) VISIBLE,
  "TEACHER_ID" NUMBER(11,0) VISIBLE,
  "HEADMASTER_ID" NUMBER(11,0) VISIBLE,
  "IS_FM_NID_DUPLICATE" NUMBER(11,0) VISIBLE DEFAULT '0'
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."NATIONALITY" IS '1=বাংলাদেশি,2=অন্যান্য';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."RELIGION" IS '1=ইসলাম,2=হিন্দু,3=বৌদ্ধ,4=খ্রিষ্টান,5=Not a believer,6=Refuse to disclose,7=অন্যান্য';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."REGISTER_CLASS" IS '6=৬ষ্ঠ,7=৭ম,8=৮ম,9=৯ম,5=10ম ,11=১১শ,12=১২শ';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."MARITAL_STATUS" IS '1=অবিবাহিত ,2=বিবাহিত ,3=বিধবা / বিপত্নীক,4=স্বামী-স্ত্রী পৃথক বসবাস ,5=তালাকপ্রাপ্ত / বিবাহ বিচ্ছেদ';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."IS_DISABILITY" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."DISABILITYTYPE" IS '1= বাক প্রতিবন্ধী ,2= দৃষ্টি প্রতিবন্ধী ,3= শ্রবন প্রতিবন্ধী,4= শারীরিক প্রতিবন্ধী,5= মানসিক প্রতিবন্ধী,6= সমস্যা নেই ';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."BLOOD_GROUP" IS '1=A+ ,2=A-,3=B+,4=B-,5=AB+,6=AB-,7=O+ ,8=O-';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."SMALL_ETHNIC_GROUP" IS '1=yes,0=no';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."SMALL_ETHNIC_GROUP_NAME" IS '1=সাওতাল,2=চাকমা,3=গারো,4=হাজং,5=চাক,6=কুকি,7=খেয়া,8=বম,9=মারমা,10=ত্রিপুরা,11=খাসিয়া,12=মনিপুরী,13=অন্যান্য,';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."RELATIONSHIP_WITH_GUARDIAN" IS '1=দাদা ,2=দাদি,3=ভাই ,4=বোন ,5= চাচা ,6=নানা ,7=নানী ,8=মামা,9=ফুফু ,10=খালা ,11=চাচাতো ভাই,12=মামাতো ভাই,13=চাচাতো বোন,14=মামাতো বোন,15=আইনগত';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."CERTIFICATION_STATUS" IS 'yes=2,no=1';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."ID_CARD_GENERATE_STATUS" IS '0=not generate id card,1=generated id card';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."FM_NID_FOUND_STATUS" IS '0=not found,1=found';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."STD_BIRTH_REG_NO_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."UID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."MOTHER_NID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."FATHER_NID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."GUARDIAN_NID_STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."TEMP_STATUS" IS '1=for next operation,0=not ready yet';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."STATUS" IS '0=pending,1=Verified,2=invalid';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."BRN_FATHER_NAME_EN_STATUS" IS '0=pending; 1 = verified';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."BRN_FATHER_NAME_BN_STATUS" IS '0=pending; 1 = verified';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."BRN_MOTHER_NAME_EN_STATUS" IS '0=pending; 1 = verified';
COMMENT ON COLUMN "CRVSPROD"."STD_REGISTRATION_INFO"."BRN_MOTHER_NAME_BN_STATUS" IS '0=pending; 1 = verified';

-- ----------------------------
-- Table structure for STD_SUBJECT_WISE_RESULTS
-- ----------------------------
DROP TABLE "CRVSPROD"."STD_SUBJECT_WISE_RESULTS";
CREATE TABLE "CRVSPROD"."STD_SUBJECT_WISE_RESULTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "SCAI_ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "TOTAL_NUMBER" VARCHAR2(3 BYTE) VISIBLE,
  "GRADE_POINTS" VARCHAR2(5 BYTE) VISIBLE,
  "EXAM_YEAR" VARCHAR2(4 BYTE) VISIBLE,
  "SUBJECT_ID" NUMBER(10,0) VISIBLE,
  "OPTIONAL_SUBJECT_STATUS" NUMBER(3,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SUBJECTS
-- ----------------------------
DROP TABLE "CRVSPROD"."SUBJECTS";
CREATE TABLE "CRVSPROD"."SUBJECTS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "CLASS_ID" NUMBER(10,0) VISIBLE,
  "NAME" VARCHAR2(150 BYTE) VISIBLE,
  "CODE" VARCHAR2(6 BYTE) VISIBLE,
  "TOTAL_MARK" VARCHAR2(3 BYTE) VISIBLE,
  "INSTITUTE_TYPE_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "SUBJECT_TYPE" NUMBER(10,0) VISIBLE DEFAULT '1'  NOT NULL,
  "GROUP_TYPE" NUMBER(10,0) VISIBLE,
  "EXAM_ID" NUMBER(10,0) VISIBLE,
  "SUB_GROUP" NUMBER(10,0) VISIBLE,
  "STATUS" NUMBER(3,0) VISIBLE DEFAULT '1'  NOT NULL,
  "CREATED_BY" VARCHAR2(255 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(255 BYTE) VISIBLE,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."SUBJECTS"."SUBJECT_TYPE" IS '1=আবশ্যিক বিষয় 2=ঐচ্ছিক বিষয়,3= নৈর্বাচনিক বিষয়';
COMMENT ON COLUMN "CRVSPROD"."SUBJECTS"."GROUP_TYPE" IS '1= মানবিক , 2= বিজ্ঞান , 3=ব্যবসায় শিক্ষা, 4= ইসলাম শিক্ষা , 5=গার্হস্থ্য বিজ্ঞান ,6= সংগীত ';
COMMENT ON COLUMN "CRVSPROD"."SUBJECTS"."SUB_GROUP" IS 'for option&elective subject which subject are show in same dropdown list';

-- ----------------------------
-- Table structure for THANAS
-- ----------------------------
DROP TABLE "CRVSPROD"."THANAS";
CREATE TABLE "CRVSPROD"."THANAS" (
  "THANA_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "DISTRICT_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "THANA_ID_NEW" NUMBER(10,0) VISIBLE,
  "THANA_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "THANA_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "THANA_NAMEB" VARCHAR2(150 BYTE) VISIBLE,
  "AREA_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "DISTRICT_HQ" VARCHAR2(50 BYTE) VISIBLE,
  "M_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "SEQEAP" VARCHAR2(50 BYTE) VISIBLE,
  "POP07" VARCHAR2(50 BYTE) VISIBLE,
  "SEAT_NO" VARCHAR2(50 BYTE) VISIBLE,
  "DURGAM" VARCHAR2(50 BYTE) VISIBLE,
  "STAT" VARCHAR2(50 BYTE) VISIBLE,
  "MPO_APP_NOT_THANA" NUMBER(10,0) VISIBLE,
  "UICTTRCE" NUMBER(10,0) VISIBLE,
  "UITRCE_SUPPORT_THANA" NUMBER(10,0) VISIBLE,
  "UICT_SUPPORT_THANA" NUMBER(10,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for UNIONS
-- ----------------------------
DROP TABLE "CRVSPROD"."UNIONS";
CREATE TABLE "CRVSPROD"."UNIONS" (
  "UNION_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "THANA_ID" VARCHAR2(15 BYTE) VISIBLE NOT NULL,
  "UNION_ID_NEW" VARCHAR2(50 BYTE) VISIBLE,
  "THANA_ID_NEW" VARCHAR2(50 BYTE) VISIBLE,
  "UNION_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "UNION_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "UNION_NAMEB" VARCHAR2(150 BYTE) VISIBLE,
  "ENTERED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "ENTRY_TIMESTAMP" DATE VISIBLE,
  "SIDR_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_BY" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_UPDATED_TIMESTAMP" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "CRVSPROD"."USERS";
CREATE TABLE "CRVSPROD"."USERS" (
  "ID" NUMBER(19,0) VISIBLE NOT NULL,
  "NAME" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(255 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(255 BYTE) VISIBLE,
  "EMAIL_VERIFIED_AT" TIMESTAMP(6) VISIBLE,
  "PASSWORD" VARCHAR2(255 BYTE) VISIBLE NOT NULL,
  "REMEMBER_TOKEN" VARCHAR2(100 BYTE) VISIBLE,
  "DIVISION_ID" NUMBER(10,0) VISIBLE,
  "DISTRICT_ID" NUMBER(10,0) VISIBLE,
  "THANA_ID" NUMBER(10,0) VISIBLE,
  "UNION_ID" NUMBER(10,0) VISIBLE,
  "CREATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "UPDATED_BY" VARCHAR2(20 BYTE) VISIBLE,
  "ROLES" NUMBER(3,0) VISIBLE NOT NULL,
  "CREATED_AT" TIMESTAMP(6) VISIBLE,
  "UPDATED_AT" TIMESTAMP(6) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "CRVSPROD"."USERS"."ROLES" IS '1=Super Admin,2 = admin';

-- ----------------------------
-- View structure for BY_GEO_AND_DATE_WISE_TOTAL_FMG_INFO
-- ----------------------------
